export BUN_HOME=/opt/bun/bin
export JAVA_HOME=/opt/jdk-24.0.1
export GRADLE_HOME=/opt/gradle-8.14
export NODE_HOME=/opt/node-v24.2.0-linux-x64

export PATH=$PATH:$JAVA_HOME/bin:$BUN_HOME/bin:$GRADLE_HOME/bin:$NODE_HOME/bin
